### ISSUE TITLE
About Repo's Topology

### ISSUE THREAD

**Issue by mintyfrankie** [mintyfrankie/brilliant-CV-Submodule#17]
The Topology of the `brilliant-CV` project has always been an issue for me, as we have to balance between maintainability and flexibility.

While the use of submodule for the template folder can allow users to follow and update changes on the template file itself, it is rather hard to maintain an unified commit history, issues as well as PRs, which makes the project more prone to bugs. 

Any advice is sincerely welcome on this matter!

**Comment by saveriogzz** [comment]
hey @mintyfrankie! This is very good point, thanks for raising it.
When I approached the project as a user, I thought that the chance you gave by setting the project as a template was a really good setup. As a contributor, instead, I found it somewhat cumbersome to come here to the submodule and request the changes to the template.  
How terrible would it be to have everything in a single repository, with some `Contribution guidelines` defined, for someone willing to contribute to the template or the project in general?

**Comment by mintyfrankie** [comment]
Indeed! It was definitely not ideal to develop a project like this.

However I find it also pity to have a single repository (in this case rather keeping the `submodule` one I imagine) without the possibility of demonstrating and guiding the user how to use it, especially when one has to setup the project structure and download the font files manually. That's a huge trade-off in my opinion.

I was thinking about two potential pathways when developing this template:

1. If Typst has a more capable project-oriented CLI, we might benefit from some interface to help users set up the skeleton code by executing something like `typst create project`. By doing this, we don't necessarily need to maintain a demonstration repo any more. 

2. If Typst in the future extends its package feature for templates too, then the maintenance attention will surely focus on the `submodule` one. This provides also possibility for the users to update their template files while keeping their content.
