### ISSUE TITLE
Setting `varEntrySocietyFirst` and formatting of `location`/`date`

### ISSUE THREAD

**Issue by agerlach** [mintyfrankie/brilliant-CV-Submodule#23]
When setting`varEntrySocietyFirst = true`, the society and title switch locations and formatting as expected. However, the location and date does not also switch. It seems logical to me that the society and location should always be together (same line) and so should the title and date.

Current:
<img width="1068" alt="image" src="https://github.com/mintyfrankie/brilliant-CV-Submodule/assets/599421/1d33b52f-def6-46c4-b7a2-10f9a9fdad40">

Proposed:
<img width="1069" alt="image" src="https://github.com/mintyfrankie/brilliant-CV-Submodule/assets/599421/ea45ca3b-231f-4e7d-93ad-9125e34c497f">

I have this currently working, but it is a complete hack. I am a Typst newb.

**Comment by mintyfrankie** [comment]
Hi @agerlach, the latest commit should have already fixed this issue. Feel free to have a check!

Close this issue now, thanks!

**Comment by agerlach** [comment]
The latest commit produces the following. The location and date are switched as expected, but I think the formating should  e.g. blue. I mentioned this in the OP, but it may not have been clear.

<img width="974" alt="image" src="https://github.com/mintyfrankie/brilliant-CV-Submodule/assets/599421/85dcfe8b-bd46-4e5d-932e-a5048b3ccf2b">
